### ISSUE TITLE
Intermittent failures in `t/03_ufuncs.t` line 76 with recent PDL

### ISSUE THREAD

**Issue by mohawk2** [moocow-the-bovine/PDL-CCS#10]
Occasionally, PDL's CI has started failing when downstream-testing CCS. It's always this, which means there's something non-deterministic happening:

```
#8 55.37 
#8 55.37 #   Failed test 'qsorti:missing=255:vals
#8 55.37 #   :     got=(indx) 
#8 55.37 # [
#8 55.37 #  [ 4  0 -1 -1 -1]
#8 55.37 #  [ 0  1 -1 -1 -1]
#8 55.37 #  [ 3  1  2 -1 -1]
#8 55.37 #  [ 0  4  3  2 -1]
#8 55.37 #  [ 4  1  3 -1 -1]
#8 55.37 #  [ 1 -1 -1 -1 -1]
#8 55.37 # ]
#8 55.37 # 
#8 55.37 #   :  wanted=(indx) 
#8 55.37 # [
#8 55.37 #  [ 4  0 -1 -1 -1]
#8 55.37 #  [ 0  1 -1 -1 -1]
#8 55.37 #  [ 3  1  2 -1 -1]
#8 55.37 #  [ 0  4  3  2 -1]
#8 55.37 #  [ 4  1  3 -1 -1]
#8 55.37 #  [ 4 -1 -1 -1 -1]
#8 55.37 # ]
#8 55.37 # '
#8 55.37 #   at t/03_ufuncs.t line 76.
```

Any ideas?

**Comment by moocow-the-bovine** [comment]
@mohawk2 
> Any ideas?

My only thought is that maybe something non-deterministic might be going on in `PDL::qsorti` (for `wanted`) and/or `PDL::qsortveci` (for `got`)?  If the underlying sort isn't guaranteed to be stable (maybe using a random pivot element?), then that could cause weird intermittent failures I guess.  I haven't followed this all the way down even the CCS-internal rabbit hole, but that's my best guess at the moment.

**Comment by mohawk2** [comment]
It turns out the problem was in `enumvec`. Annoyingly, a little while ago I'd seen `valgrind` tell me there was a problem, but I couldn't see it at the time so thought it was a false positive (which does occasionally happen).

The original code had `kn` which went up to the highest value for index `N`, but then always got `++` before being used in comparing the values of vectors. This meant it could and would run off the end of the input. When the code gave the right results, it was because the value(s) it read in the off-the-end vector happened to not match the one being compared to, but occasionally it would erroneously match, so the code would occasionally give test failures.

The commit above adds extra logic to check, on matching, whether it is the highest valid value of `N`, and if so it arranges to stop. This enables a reordering of the rest of the logic so it can look at the current `N`, not needing to go one above. `valgrind` reports no errors, and the tests from CCS (which I've brought into main PDL to capture the required behaviour in there) pass.

I'm going to close this, though I might reopen if it turns out I missed something!

**Comment by moocow-the-bovine** [comment]
> always got `++` before being used in comparing the values of vectors

oops. definitely my bad, sorry. looking at https://github.com/PDLPorters/pdl/commit/37233bb , I do see the problem.  Good catch, thanks for tracking that down!

**Comment by mohawk2** [comment]
Very welcome! You may notice the code I was changing in that recent commit wasn't quite your original, but it was semantically equivalent. I suspect that my changes, while semantically null, made the optimiser generate different code, which generated the occasional fails.
